/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x8.h"
#include "stm32f103x8_exti_drivers.h"
#include "stm32f103x8_gpio_drivers.h"
#include "stm32f103x8_uart_drivers.h"
#include "stm32f103x8_rcc_drivers.h"
#include "LCD.h"
#include "keypad.h"


//uint8_t IRQ_Flag;
//
//void wait_ms(int x){
//	unsigned int i ,j;
//	for(i = 0 ; i < x ; i++){
//		for(j = 0 ; j < 255 ; j++);
//	}
//}

unsigned char ch ;

int main(void){
	//Enable CLK
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
//	HAL_LCD_INIT();
//	HAL_LCD_CLEAR_SCREEN();

	USART_Config_t uartCFG;

	uartCFG.BaudRate = USART_BaudRate_115200;
	uartCFG.HW_Ctrol = USART_HW_FlowCtrl_NONE;
	uartCFG.IRQ_Enable = USART_IRQ_Enable_NONE;
	uartCFG.USART_MODE = UART_MODE_TX_RX;
	uartCFG.data_len = USART_data_Length_8B;
	uartCFG.p_IRQ_call_back = NULL;
	uartCFG.parity = USART_Parity_NONE;
	uartCFG.stop_bits = USART_StopBits_1;

	MCAL_UART_INIT(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);


	while(1){
		MCAL_UART_RECEIVE_DATA(USART1, &ch, enable);
		MCAL_UART_SEND_DATA(USART1, &ch, enable);
	}

}
