/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t;
#include <stdio.h>


#define RCC_BASE       0x40021000
#define GPIO_PortA 	   0x40010800
#define APB2ENR        *((vuint32_t *)(RCC_BASE   + 0x18))
#define CRH    	       *((vuint32_t *)(GPIO_PortA + 0x04))
#define GPIOA_ODR      *((vuint32_t *)(GPIO_PortA + 0x0C))


int main(void) {

	APB2ENR |= (1<<2);
	CRH &= 0xFF0FFFFF;
	CRH |= 0x00200000;

	while(1){
		GPIOA_ODR |= 1<<13;
		for(int i = 0 ; i < 6000 ; i++);
		GPIOA_ODR &= ~(1<<13);
		for(int i = 0 ; i < 6000 ; i++);
	}
	return 0;
}
